# Generated by Django 4.1.7 on 2023-11-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("used_book", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="UsedBook",
        ),
    ]
