# Generated by Django 4.1.7 on 2023-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_book", "0002_rename_book_usedbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="usedbook",
            name="category",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non-fiction", "Non-Fiction"),
                    ("fantasy", "Fantasy"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
