# Generated by Django 4.1.7 on 2023-11-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_book', '0004_alter_usedbook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbook',
            name='price',
            field=models.IntegerField(),
        ),
    ]
