# Generated by Django 4.1.7 on 2023-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_book", "0006_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usedbook",
            name="image",
            field=models.ImageField(blank=True, upload_to="books/"),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
