# Generated by Django 4.1.7 on 2023-11-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_book", "0008_image_remove_usedbook_image_usedbook_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usedbook",
            name="image",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddField(
            model_name="usedbook",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
