# Generated by Django 4.1.7 on 2023-11-30 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("used_book", "0009_remove_usedbook_image_delete_image_usedbook_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usedbook",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="usedbook",
            name="image",
        ),
        migrations.AddField(
            model_name="usedbook",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="used_book.photo"
            ),
        ),
    ]
