# Generated by Django 4.1.7 on 2023-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("used_book", "0010_photo_usedbook_user_remove_usedbook_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usedbook",
            name="image",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.AddField(
            model_name="usedbook",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
