# Generated by Django 4.2.7 on 2023-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_book', '0011_remove_usedbook_image_delete_photo_usedbook_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='usedbook',
            name='image',
            field=models.ImageField(default=1, upload_to='books/'),
            preserve_default=False,
        ),
    ]
