# Generated by Django 4.2.5 on 2023-11-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_book', '0012_alter_usedbook_image_detailimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedbook',
            name='detail_image',
        ),
        migrations.AddField(
            model_name='usedbook',
            name='detail_images',
            field=models.ManyToManyField(to='used_book.detailimage'),
        ),
    ]
