# Generated by Django 4.1.7 on 2023-11-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("used_book", "0012_comment_alter_usedbook_image"),
        ("used_book", "0013_remove_usedbook_detail_image_usedbook_detail_images"),
    ]

    operations = []
