# Generated by Django 4.2.7 on 2023-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_book', '0014_merge_20231201_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbook',
            name='image',
            field=models.ImageField(null=True, upload_to='books/'),
        ),
    ]
