# Generated by Django 4.1.7 on 2023-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_book', '0003_department_subdepartment_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
