# Generated by Django 4.1.7 on 2023-11-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
