# Generated by Django 4.1.7 on 2023-11-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0002_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcart',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subdepartment',
            name='department',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookCart',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='SubDepartment',
        ),
    ]
