# Generated by Django 4.2.5 on 2023-10-19 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from django.db import migrations, models

def set_default_department(apps, schema_editor):
    
    Book = apps.get_model('book', 'Book')
    Department = apps.get_model('book', 'Department')

    try:
       
        default_department, created = Department.objects.get_or_create(name='Default Department')

        
        for book in Book.objects.all():
            if not book.department:
                book.department = default_department
                book.save()
    except Department.DoesNotExist:
        
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(on_delete=models.CASCADE, to='book.Department', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_department),
    ]
