# Generated by Django 4.2.5 on 2023-10-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_department_book_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='book_Department',
        ),
    ]
