# Generated by Django 4.2.5 on 2023-10-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_department_book_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='department',
        ),
        migrations.DeleteModel(
            name='book_Department',
        ),
    ]
