# Generated by Django 4.2.5 on 2023-10-19 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('kkak', 'zzzzz')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
