# Generated by Django 4.2.5 on 2023-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_department_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
