# Generated by Django 4.2.5 on 2023-10-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_subdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='book.department'),
        ),
    ]
