# Generated by Django 4.2.5 on 2023-10-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_subdepartment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='department',
        ),
        migrations.AddField(
            model_name='book',
            name='sub_department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.subdepartment'),
        ),
    ]
