# Generated by Django 4.1.7 on 2023-11-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_rename_auther_book_author_book_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='stock',
        ),
    ]
