# Generated by Django 4.1.7 on 2023-11-07 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookAdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookName", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("publisher", models.CharField(max_length=255)),
                (
                    "publicationDate",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("volume", models.IntegerField()),
                ("remarks", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("isbn", models.CharField(max_length=13)),
            ],
        ),
    ]
