# Generated by Django 4.1.7 on 2023-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookadd",
            name="publicationDate",
        ),
        migrations.AddField(
            model_name="bookadd",
            name="publicationYear",
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookadd",
            name="remarks",
            field=models.CharField(max_length=50),
        ),
    ]
